//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3082.
// 
namespace ClsRampdb.Synchronize {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SynchroniseSoap", Namespace="http://tempuri.org/")]
    public partial class Synchronise : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Synchronise() {
            this.Url = "http://vijay/rampService/Synchronise.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SyncTables", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SyncTables(string sdate, string sTableName, out System.DateTime dtOutDate) {
            object[] results = this.Invoke("SyncTables", new object[] {
                        sdate,
                        sTableName});
            dtOutDate = ((System.DateTime)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSyncTables(string sdate, string sTableName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SyncTables", new object[] {
                        sdate,
                        sTableName}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndSyncTables(System.IAsyncResult asyncResult, out System.DateTime dtOutDate) {
            object[] results = this.EndInvoke(asyncResult);
            dtOutDate = ((System.DateTime)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SyncTableswithItemLimit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SyncTableswithItemLimit(string sdate, string sTableName, long Itemlimit, out System.DateTime dtOutDate) {
            object[] results = this.Invoke("SyncTableswithItemLimit", new object[] {
                        sdate,
                        sTableName,
                        Itemlimit});
            dtOutDate = ((System.DateTime)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSyncTableswithItemLimit(string sdate, string sTableName, long Itemlimit, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SyncTableswithItemLimit", new object[] {
                        sdate,
                        sTableName,
                        Itemlimit}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndSyncTableswithItemLimit(System.IAsyncResult asyncResult, out System.DateTime dtOutDate) {
            object[] results = this.EndInvoke(asyncResult);
            dtOutDate = ((System.DateTime)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAssets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AddAssets(System.Data.DataTable dtTable) {
            object[] results = this.Invoke("AddAssets", new object[] {
                        dtTable});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddAssets(System.Data.DataTable dtTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddAssets", new object[] {
                        dtTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndAddAssets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TagWrite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TagWrite(System.Data.DataTable dtTable) {
            object[] results = this.Invoke("TagWrite", new object[] {
                        dtTable});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTagWrite(System.Data.DataTable dtTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TagWrite", new object[] {
                        dtTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndTagWrite(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModifyAssets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ModifyAssets(System.Data.DataTable dtTable) {
            object[] results = this.Invoke("ModifyAssets", new object[] {
                        dtTable});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginModifyAssets(System.Data.DataTable dtTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ModifyAssets", new object[] {
                        dtTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndModifyAssets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InventoryCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable InventoryCheck(System.Data.DataTable dtClientTbl) {
            object[] results = this.Invoke("InventoryCheck", new object[] {
                        dtClientTbl});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInventoryCheck(System.Data.DataTable dtClientTbl, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InventoryCheck", new object[] {
                        dtClientTbl}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndInventoryCheck(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FieldServiceCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable FieldServiceCheck(System.Data.DataTable dtTable) {
            object[] results = this.Invoke("FieldServiceCheck", new object[] {
                        dtTable});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFieldServiceCheck(System.Data.DataTable dtTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FieldServiceCheck", new object[] {
                        dtTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndFieldServiceCheck(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AddLocation(System.Data.DataTable dtTable) {
            object[] results = this.Invoke("AddLocation", new object[] {
                        dtTable});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddLocation(System.Data.DataTable dtTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddLocation", new object[] {
                        dtTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndAddLocation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddPerformedTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AddPerformedTask(System.Data.DataTable dtTable) {
            object[] results = this.Invoke("AddPerformedTask", new object[] {
                        dtTable});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddPerformedTask(System.Data.DataTable dtTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddPerformedTask", new object[] {
                        dtTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndAddPerformedTask(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateFS_AssetStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable UpdateFS_AssetStatus(System.Data.DataTable dtTable) {
            object[] results = this.Invoke("UpdateFS_AssetStatus", new object[] {
                        dtTable});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateFS_AssetStatus(System.Data.DataTable dtTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateFS_AssetStatus", new object[] {
                        dtTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndUpdateFS_AssetStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateFS_AssetStatus1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateFS_AssetStatus1(long ID_FSAssetStaus, int FSStatus, int TaskStatus, long ModifiedBy, System.DateTime ModifiedDate, string Comments) {
            object[] results = this.Invoke("UpdateFS_AssetStatus1", new object[] {
                        ID_FSAssetStaus,
                        FSStatus,
                        TaskStatus,
                        ModifiedBy,
                        ModifiedDate,
                        Comments});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateFS_AssetStatus1(long ID_FSAssetStaus, int FSStatus, int TaskStatus, long ModifiedBy, System.DateTime ModifiedDate, string Comments, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateFS_AssetStatus1", new object[] {
                        ID_FSAssetStaus,
                        FSStatus,
                        TaskStatus,
                        ModifiedBy,
                        ModifiedDate,
                        Comments}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUpdateFS_AssetStatus1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddFSStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AddFSStatus(System.Data.DataTable dtTable) {
            object[] results = this.Invoke("AddFSStatus", new object[] {
                        dtTable});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddFSStatus(System.Data.DataTable dtTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddFSStatus", new object[] {
                        dtTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndAddFSStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AddEmployee(System.Data.DataTable dtTable) {
            object[] results = this.Invoke("AddEmployee", new object[] {
                        dtTable});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddEmployee(System.Data.DataTable dtTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddEmployee", new object[] {
                        dtTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndAddEmployee(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFSbyLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetFSbyLocation(long ID_Location) {
            object[] results = this.Invoke("GetFSbyLocation", new object[] {
                        ID_Location});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetFSbyLocation(long ID_Location, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetFSbyLocation", new object[] {
                        ID_Location}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetFSbyLocation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
    }
}
